// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_mkbAtDPbksX55I_zrJSF190uqYyPgP8',
    appId: '1:719170666797:web:ebe04baf4cecad9e3453a4',
    messagingSenderId: '719170666797',
    projectId: 'noteapp-e11e5',
    authDomain: 'noteapp-e11e5.firebaseapp.com',
    storageBucket: 'noteapp-e11e5.firebasestorage.app',
    measurementId: 'G-15SVCEBFBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVbFGDqhDS2_ZaTgrVJTYCN41YQIwUr7I',
    appId: '1:719170666797:android:b98d41eff5cc4a433453a4',
    messagingSenderId: '719170666797',
    projectId: 'noteapp-e11e5',
    storageBucket: 'noteapp-e11e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDINKt4OdQqz9_cZRG2Y0KiUCSfySfO96c',
    appId: '1:719170666797:ios:d5df40d74cdb4ab93453a4',
    messagingSenderId: '719170666797',
    projectId: 'noteapp-e11e5',
    storageBucket: 'noteapp-e11e5.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDINKt4OdQqz9_cZRG2Y0KiUCSfySfO96c',
    appId: '1:719170666797:ios:d5df40d74cdb4ab93453a4',
    messagingSenderId: '719170666797',
    projectId: 'noteapp-e11e5',
    storageBucket: 'noteapp-e11e5.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_mkbAtDPbksX55I_zrJSF190uqYyPgP8',
    appId: '1:719170666797:web:59986f66237f4b753453a4',
    messagingSenderId: '719170666797',
    projectId: 'noteapp-e11e5',
    authDomain: 'noteapp-e11e5.firebaseapp.com',
    storageBucket: 'noteapp-e11e5.firebasestorage.app',
    measurementId: 'G-BSF15JT21C',
  );
}
